name: linter

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos

  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath
          tools: composer:v2
          coverage: none

      - name: Add Flux Credentials
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run Pint
        run: ./vendor/bin/pint --test